# Generated by Django 5.2.17 on 2026-09-14 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_itemimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='packages', to='products.collection'),
        ),
    ]
