# Generated by Django 5.2.17 on 2026-09-14 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_package_collection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='packages', to='products.collection'),
        ),
    ]
