# Generated by Django 5.2.17 on 2026-08-16 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_phoneverificationotp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phoneverificationotp',
            name='user',
        ),
        migrations.AddField(
            model_name='phoneverificationotp',
            name='purpose',
            field=models.CharField(choices=[('LOGIN', 'Login'), ('PHONE_CHANGE', 'Phone Change'), ('EMAIL_VERIFICATION', 'Email Verification')], default='PHONE_CHANGE', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='profile_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='phoneverificationotp',
            name='phone_number',
            field=models.CharField(db_index=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, db_index=True, max_length=15, null=True, unique=True),
        ),
    ]
