# Generated by Django 5.2.17 on 2026-08-18 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_emailverificationotp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phoneverificationotp',
            name='purpose',
            field=models.CharField(choices=[('LOGIN', 'Login'), ('PHONE_CHANGE', 'Phone Change')], max_length=30),
        ),
    ]
