# Generated by Django 5.2.17 on 2026-09-09 06:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_promotion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='promotion_usages', to=settings.AUTH_USER_MODEL)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='promotion_usage', to='inventory.order')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usages', to='inventory.promotion')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['promotion', 'customer'], name='promotion_customer_idx'), models.Index(fields=['customer', '-created_at'], name='promotion_usage_customer_idx')],
            },
        ),
    ]
