# Generated by Django 5.2.17 on 2026-09-12 09:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_order_discount_amount'),
        ('products', '0002_package_packageitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField()),
                ('review', models.TextField(blank=True)),
                ('is_approved', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='products.item')),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='products.package')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('item__isnull', False), ('package__isnull', False), _connector='OR'), name='review_has_product'), models.CheckConstraint(condition=models.Q(('item__isnull', True), ('package__isnull', True), _connector='OR'), name='review_only_one_product'), models.CheckConstraint(condition=models.Q(('rating__gte', 1), ('rating__lte', 5)), name='review_rating_1_to_5'), models.UniqueConstraint(condition=models.Q(('item__isnull', False)), fields=('customer', 'item'), name='unique_customer_item_review'), models.UniqueConstraint(condition=models.Q(('package__isnull', False)), fields=('customer', 'package'), name='unique_customer_package_review')],
            },
        ),
    ]
